Models/Question.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Asp.net_Project.Models
{
    public class Question
    {
        
        public int id { get; set; }

        [Required] // Foreign key
        public int asked_by_who_id { get; set; }

        [Required] // Foreign Key
        public string asked_by_who_name { get; set; }

        [Required]
        public string categorie { get; set; }

        [Required]
        public string classedestination { get; set; }

        [Required]
        public string queston_title { get; set; }

        [Required]
        public string question_detail { get; set; }

        public DateTime asking_date { get; set; }

    }

   
}

Controllers/AnswerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Asp.net_Project.Models;

namespace Asp.net_Project.Controllers
{
    public class AnswerController : Controller
    {

        private ConfigDB db = new ConfigDB();

        public ActionResult show()
        {
            var LL = from a in db.Answers orderby a.id select a;
            return View(LL);

        }


        public ActionResult answer_question(int id)
        {

            if ((int)Session["userid"] == 0)
            {
                return RedirectToAction("Login", "User");
            }
            else
            {
                Session["question_id"] = id;


                return View();
            }
        }

        [HttpPost]
        public ActionResult answer_question(Answer ans)
        {

            Answer answer = new Answer();

            try
            {
                int question_id_to_answer = (int)Session["question_id"];

                answer.question_id = question_id_to_answer;
                answer.answer = ans.answer;
                answer.answerd_by_id = (int)Session["userid"];
                answer.answerd_by_name = Session["userfname"].ToString() + " " + Session["userlname"].ToString();
                answer.datatime_answering = DateTime.Now;

                db.Answers.Add(answer);
                db.SaveChanges();

                return RedirectToAction("Index" , "Question");


            }
            catch
            {

                return View();
            }
        }


        public ActionResult See_Other_Answers(int id)
        {
            var L1 = from answers in db.Answers where answers.question_id.Equals(id) select answers;
            return View(L1);
        }


    }
}

Controllers/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Asp.net_Project.Models;
using Asp.net_Project.Controllers;

namespace Asp.net_Project.Controllers
{
    public class QuestionController : Controller
    {

        //private QuestionDBContext db = new QuestionDBContext();

        // private UserDBContext dbusers = new UserDBContext();

        private ConfigDB db = new ConfigDB();


        public ActionResult show()
        {
            var LL = from q in db.Questions orderby q.id select q;
            return View(LL);

        }

        

        // GET: Question
        public ActionResult Index() // here we select * from table where categorie = public 
        {
            var L = from q in db.Questions where q.classedestination.Equals("Public Question") select q;
            return View(L);
        }


        public ActionResult Ask_Question()
        {
            if ((int)Session["userid"] == 0)
            {
                return RedirectToAction("Login", "User");
            }
            else {
                return View();
            }
        }

        [HttpPost]
        public ActionResult Ask_Question(Question Qes)
        {
            

           

                Question question = new Question();

                try
                {
                    //HERE WE SELECT NAME FROM USER WHERE ID = ID (THIS ID FROM SESSION IJBERE !!)
                    //W HEDA L2ESEM B7OTTO BL question.asked_by_who. 


                    question.asked_by_who_id = (int)Session["userid"];
                    question.asked_by_who_name = Session["userfname"].ToString() + " " + Session["userlname"].ToString();
                    question.categorie = Qes.categorie;
                    question.classedestination = Qes.classedestination;
                    question.queston_title = Qes.queston_title;
                    question.question_detail = Qes.question_detail;
                    question.asking_date = DateTime.Now;

                    db.Questions.Add(question);
                    db.SaveChanges();

                    return RedirectToAction("Index");

                }
                catch
                {
                    return View();
                }
            
        }




        public ActionResult Direst_Question_For_Me()
        {

            int myid = (int)Session["userid"];
            var l = from qes in db.Questions where qes.classedestination.Equals(myid.ToString()) select qes;

            return View(l);
        }

        public ActionResult Direct_Question_Within_My_Promotion()
        {
            // get the id from session ymknnn :(  , we bs7ab lclass halle ele min user table.
            //brja3 b3ml list btsewe select from question where classdestination = halle s7bata abla 
            // w b3abbe hlist blview .

            if ((int)Session["userid"] == 0)
            {
                return RedirectToAction("Login", "User");
            }
            else
            {
                string prom = Session["promotion"].ToString();
                var l = from qe in db.Questions where qe.classedestination.Equals(prom) select qe;
                return View(l);
            }

           // return View();
        }

        public ActionResult Academic_Question()
        {
            var L = from q in db.Questions where q.categorie.Equals("Academic Question") & q.classedestination.Equals("Public Question")  select q;
            return View(L);
            
        }

        public ActionResult Management_Question()
        {
            var L = from q in db.Questions where q.categorie.Equals("Management Question") & q.classedestination.Equals("Public Question") select q;
            return View(L);
            ;
        }

        public ActionResult Miscellaneous_Question()
        {
            var L = from q in db.Questions where q.categorie.Equals("Miscellaneous Question") & q.classedestination.Equals("Public Question") select q;
            return View(L);
            
        }

        public ActionResult list_of_my_question()
        {
            int myid = (int)Session["userid"];
            var list_of_question = from q in db.Questions where q.asked_by_who_id.Equals(myid) select q;
            return View(list_of_question);
        }




        
        public ActionResult Ask_Him_Question(int id)
        {
            if ((int)Session["userid"] == 0)
            {
                return RedirectToAction("Login", "User");
            }
            else
            {
                Session["userid_foraskhim"] = id;
                return View();
            }
        }

        [HttpPost]
        public ActionResult Ask_Him_Question(Question Qes)
        {




            Question question = new Question();

            try
            {
                int iddestination = (int)Session["userid_foraskhim"];

                //var fname = from fn in db.Users where fn.id.Equals(iddestination) select fn.fname;

               


                question.asked_by_who_id = (int)Session["userid"];
                question.asked_by_who_name = Session["userfname"].ToString() + " " + Session["userlname"].ToString();
                question.categorie = Qes.categorie;
                question.classedestination = iddestination.ToString();
                question.queston_title = Qes.queston_title;
                question.question_detail = Qes.question_detail;
                question.asking_date = DateTime.Now;

                db.Questions.Add(question);
                db.SaveChanges();

                return RedirectToAction("Index");

            }
            catch
            {
                return View();
            }

        }
        

    }
}

Views/Question/Academic_Question.cshtml
@model IEnumerable<Asp.net_Project.Models.Question>

@{
    ViewBag.Title = "Academic_Question";
}
<br />
<br />
<h2> Public Academic Questions</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-inline ">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <br />
        <div class="form-group">

            <div style="margin-left:360px">

                <input class="form-control" style="width:900px" type="text" placeholder="Search ... " />
                &nbsp;&nbsp;&nbsp;
                <input type="submit" value=" &nbsp;&nbsp;&nbsp;Search &nbsp;&nbsp;&nbsp;" class="btn btn-outline-primary" />
            </div>
        </div>
    </div>
}
<hr />
@{
    <h4>
        Total Question :
        @Model.ToList().Count.ToString()
        Questions

    </h4>
}
<div class="jumbotron">
    @{
        if (Model.ToList().Count == 0)
        {
            <br />
            <br />
            <h1 align="center" style="color:dodgerblue "> No Public Questions Yet  (Academic Questions </h1>
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
        }
    }


    @foreach (var item in Model)
    {


        <div class="card" style="width:1000px">

            <div class="card-body">

                <h4 class="card-title">
                    @Html.DisplayFor(modelItem => item.queston_title)

                </h4>


                <p class="card-text">

                    @Html.DisplayFor(modelItem => item.question_detail)

                </p>


                &nbsp;  &nbsp;  &nbsp;  &nbsp;  <br>


                <b> Asked By : </b>@Html.DisplayFor(modelItem => item.asked_by_who_name) &nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <b>Date : </b> @Html.DisplayFor(modelItem => item.asking_date)
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <b>Question Categorie : </b> @Html.DisplayFor(modelItem => item.categorie)
                <br /><br />
                <div class="form-inline">
                    @Html.ActionLink("Answer This Question", "answer_question", "Answer", new
                   { id = item.id }, new { @class = "btn btn-primary" })

                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

                    @Html.ActionLink("See Other Answers", "See_Other_Answers", "Answer", new
                    { id = item.id }, new { @class = "btn btn-danger" })

                    @Html.ActionLink("See His Profile", "SeeProfile", "User", new
                    { id = item.asked_by_who_id }, new { @class = "btn btn-success", @style = "margin-left:350px" })

                </div>
            </div>
        </div>

        <hr />













    }
</div>

Views/Question/Ask_Him_Question.cshtml
@model Asp.net_Project.Models.Question

@{
    ViewBag.Title = "Ask Him Question";
}

<br />
<br />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="jumbotron">
        <h2 align="center">Ask him  a question </h2>
        <hr />
        <div class="form-horizontal" align="center">


            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                <b>Question Categorie :</b>
                <div class="col-md-10">
                    @Html.DropDownList("categorie", new List<SelectListItem>()
                            {
                                new SelectListItem{Text="Acedemic Question" , Value = "Academic Question"},
                                new SelectListItem{Text="Management Question" , Value = "Management Question"},
                                 new SelectListItem{Text="Miscellaneous Question" , Value = "Miscellaneous Question"},


                            }, "Question Categorie", new { @class = "form-control col-md-8" }
                               )
                    @Html.ValidationMessageFor(model => model.categorie, "", new { @class = "text-danger" })

                </div>
            </div>


            <div class="form-group">
                <b>Question Title :</b>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.queston_title, new { htmlAttributes = new { @class = "form-control col-md-8" } })
                    @Html.ValidationMessageFor(model => model.queston_title, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2"><b>Question Detail :</b></label>

                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.question_detail, new { @class = "form-control col-md-8", @placeholder = "Question Detail..." })

                    @Html.ValidationMessageFor(model => model.question_detail, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Ask the question" class="btn btn-success" />
                </div>
            </div>
            <hr />
        </div>
    </div>
}



<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Views/Question/Direct_Question_Within_My_Promotion.cshtml
@model IEnumerable<Asp.net_Project.Models.Question>

@{
    ViewBag.Title = "Direct Question Within My Promotion Or My Class";
}
<br />
<br />
<h2>Direct Question Within My Promotion Or My Class</h2>
@{
    <h4>
        Total Question :
        @Model.ToList().Count.ToString()
        Questions

    </h4>
}
<div class="jumbotron">
    @{
        if (Model.ToList().Count == 0)
        {
            <br />
            <br />
            <h1 align="center" style="color:dodgerblue "> No  Questions Within My Promotion (Or Class) Yet ...  </h1>
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
        }
    }



    @foreach (var item in Model)
    {

        <div class="card" style="width:1000px">

            <div class="card-body">

                <h4 class="card-title">
                    @Html.DisplayFor(modelItem => item.queston_title)

                </h4>


                <p class="card-text">

                    @Html.DisplayFor(modelItem => item.question_detail)

                </p>


                &nbsp;  &nbsp;  &nbsp;  &nbsp;  <br>


                <b> Asked By : </b>@Html.DisplayFor(modelItem => item.asked_by_who_name) &nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <b>Date : </b> @Html.DisplayFor(modelItem => item.asking_date)
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <b>Question Categorie : </b> @Html.DisplayFor(modelItem => item.categorie)
                <br /><br />
                <div class="form-inline">
                    @Html.ActionLink("Answer This Question", "answer_question", "Answer", new
                   { id = item.id }, new { @class = "btn btn-primary" })

                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

                    @Html.ActionLink("See Other Answers", "See_Other_Answers", "Answer", new
{ id = item.id }, new { @class = "btn btn-danger" })

                    @Html.ActionLink("See His Profile", "SeeProfile", "User", new
                    { id = item.asked_by_who_id }, new { @class = "btn btn-success", @style = "margin-left:350px" })

                </div>
            </div>
        </div>


        <br />













    }
</div>

Views/Question/Direst_Question_For_Me.cshtml
@model IEnumerable<Asp.net_Project.Models.Question>

@{
    ViewBag.Title = "Direst Question For Me";
}
<br />
<br />
<h2>Direst Question For Me</h2>
@{
    <h4>
        Total Question :
        @Model.ToList().Count.ToString()
        Questions

    </h4>
}
<div class="jumbotron">
    @{
        if (Model.ToList().Count == 0)
        {
            <br />
            <br />
            <h1 align="center" style="color:dodgerblue ">There are no question for you yet!!  </h1>
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
        }
    }


    @foreach (var item in Model)
    {


        <div class="card" style="width:1000px">

            <div class="card-body">

                <h4 class="card-title">
                    @Html.DisplayFor(modelItem => item.queston_title)

                </h4>


                <p class="card-text">

                    @Html.DisplayFor(modelItem => item.question_detail)

                </p>


                &nbsp;  &nbsp;  &nbsp;  &nbsp;  <br>


                <b> Asked By : </b>@Html.DisplayFor(modelItem => item.asked_by_who_name) &nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <b>Date : </b> @Html.DisplayFor(modelItem => item.asking_date)
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <b>Question Categorie : </b> @Html.DisplayFor(modelItem => item.categorie)
                <br /><br />
                <div class="form-inline">
                    @Html.ActionLink("Answer This Question", "answer_question", "Answer", new
                   { id = item.id }, new { @class = "btn btn-primary" })

                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;


                    @Html.ActionLink("See Other Answers", "See_Other_Answers", "Answer", new
{ id = item.id }, new { @class = "btn btn-danger" })

                    @Html.ActionLink("See His Profile", "SeeProfile", "User", new
                    { id = item.asked_by_who_id }, new { @class = "btn btn-success", @style = "margin-left:350px" })

                </div>
            </div>
        </div>

        <br />













    }
</div>

Views/Question/Index.cshtml
@model IEnumerable<Asp.net_Project.Models.Question>


@{
    ViewBag.Title = "Index";
}

<br />
<br />
<h2>Public Questions </h2>

@*
    @{
        if (@Session["userid"].ToString().Equals("0"))
        {

        }
        else
        {
            <h6>@Session["userid"].ToString()</h6>
        }
    }

    @{
        if (@Session["userfname"] != null)
        {
            <h6>@Session["userfname"].ToString()</h6>

        }
        else
        {

        }

        if (@Session["userlname"] != null)
        {
            <h6>@Session["userlname"].ToString()</h6>

        }
        else
        {

        }

        if (@Session["promotion"] != null)
        {
            <h6>@Session["promotion"].ToString()</h6>

        }
        else
        {

        }

    }
    <br /><br />
*@
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-inline ">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <br />
        <div class="form-group">

            <div style="margin-left:360px">

                <input class="form-control" style="width:900px" type="text" placeholder="Search ... " />
                &nbsp;&nbsp;&nbsp;
                <input type="submit" value=" &nbsp;&nbsp;&nbsp;Search &nbsp;&nbsp;&nbsp;" class="btn btn-outline-primary" />
            </div>
        </div>
    </div>
}
<hr />

@{
    <h4>
        Total Question :
        @Model.ToList().Count.ToString()
        Questions

    </h4>
}


<div class="jumbotron">



    @{



        if (Model.ToList().Count == 0)
        {
            <br />
            <br />
            <h1 align="center" style="color:dodgerblue "> No Public Questions Yet  </h1>
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
        }
    }



    @foreach (var item in Model)
    {

        <div class="card" style="width:1000px">

            <div class="card-body">

                <h4 class="card-title">
                    @Html.DisplayFor(modelItem => item.queston_title)

                </h4>


                <p class="card-text">

                    @Html.DisplayFor(modelItem => item.question_detail)

                </p>


                &nbsp;  &nbsp;  &nbsp;  &nbsp;  <br>


                <b> Asked By : </b>@Html.DisplayFor(modelItem => item.asked_by_who_name) &nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <b>Date : </b> @Html.DisplayFor(modelItem => item.asking_date)
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <b>Question Categorie : </b> @Html.DisplayFor(modelItem => item.categorie)
                <br /><br />
                <div class="form-inline">
                    @Html.ActionLink("Answer This Question", "answer_question", "Answer", new
                   { id = item.id }, new { @class = "btn btn-primary" })

                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

                    @Html.ActionLink("See Other Answers", "See_Other_Answers", "Answer", new
{ id = item.id }, new { @class = "btn btn-danger" })

                    @Html.ActionLink("See His Profile", "SeeProfile", "User", new
                    { id = item.asked_by_who_id }, new { @class = "btn btn-success", @style = "margin-left:350px" })

                </div>
            </div>
        </div>



        <br />













    }
</div>

Views/Question/Management_Question.cshtml
@model IEnumerable<Asp.net_Project.Models.Question>

@{
    ViewBag.Title = "Management_Question";
}
<br />
<br />
<h2> Public Management Questions</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-inline ">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <br />
        <div class="form-group">

            <div style="margin-left:360px">

                <input class="form-control" style="width:900px" type="text" placeholder="Search ... " />
                &nbsp;&nbsp;&nbsp;
                <input type="submit" value=" &nbsp;&nbsp;&nbsp;Search &nbsp;&nbsp;&nbsp;" class="btn btn-outline-primary" />
            </div>
        </div>
    </div>
}
<hr />
@{
    <h4>
        Total Question :
        @Model.ToList().Count.ToString()
        Questions

    </h4>
}
<div class="jumbotron">
    @{
        if (Model.ToList().Count == 0)
        {
            <br />
            <br />
            <h1 align="center" style="color:dodgerblue "> No Public Questions Yet  (Management Questions </h1>
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
        }
    }


    @foreach (var item in Model)
    {



        <div class="card" style="width:1000px">

            <div class="card-body">

                <h4 class="card-title">
                    @Html.DisplayFor(modelItem => item.queston_title)

                </h4>


                <p class="card-text">

                    @Html.DisplayFor(modelItem => item.question_detail)

                </p>


                &nbsp;  &nbsp;  &nbsp;  &nbsp;  <br>


                <b> Asked By : </b>@Html.DisplayFor(modelItem => item.asked_by_who_name) &nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <b>Date : </b> @Html.DisplayFor(modelItem => item.asking_date)
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <b>Question Categorie : </b> @Html.DisplayFor(modelItem => item.categorie)
                <br /><br />
                <div class="form-inline">
                    @Html.ActionLink("Answer This Question", "answer_question", "Answer", new
                   { id = item.id }, new { @class = "btn btn-primary" })

                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

                    @Html.ActionLink("See Other Answers", "See_Other_Answers", "Answer", new
{ id = item.id }, new { @class = "btn btn-danger" })

                    @Html.ActionLink("See His Profile", "SeeProfile", "User", new
                    { id = item.asked_by_who_id }, new { @class = "btn btn-success", @style = "margin-left:350px" })

                </div>
            </div>
        </div>



        <hr />




    }
</div>

Views/Question/Miscellaneous_Question.cshtml
@model IEnumerable<Asp.net_Project.Models.Question>

@{
    ViewBag.Title = "Miscellaneaous_Question";
}
<br />
<br />
<h2> Public Miscellaneaous Questions</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-inline ">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <br />
        <div class="form-group">

            <div style="margin-left:360px">

                <input class="form-control" style="width:900px" type="text" placeholder="Search ... " />
                &nbsp;&nbsp;&nbsp;
                <input type="submit" value=" &nbsp;&nbsp;&nbsp;Search &nbsp;&nbsp;&nbsp;" class="btn btn-outline-primary" />
            </div>
        </div>
    </div>
}
<hr />
@{
    <h4>
        Total Question :
        @Model.ToList().Count.ToString()
        Questions

    </h4>
}
<div class="jumbotron">
    @{
        if (Model.ToList().Count == 0)
        {
            <br />
            <br />
            <h1 align="center" style="color:dodgerblue "> No Public Questions Yet  (Miscellaneaous Questions </h1>
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
        }
    }


    @foreach (var item in Model)
    {


        <div class="card" style="width:1000px">

            <div class="card-body">

                <h4 class="card-title">
                    @Html.DisplayFor(modelItem => item.queston_title)

                </h4>


                <p class="card-text">

                    @Html.DisplayFor(modelItem => item.question_detail)

                </p>


                &nbsp;  &nbsp;  &nbsp;  &nbsp;  <br>


                <b> Asked By : </b>@Html.DisplayFor(modelItem => item.asked_by_who_name) &nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <b>Date : </b> @Html.DisplayFor(modelItem => item.asking_date)
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <b>Question Categorie : </b> @Html.DisplayFor(modelItem => item.categorie)
                <br /><br />
                <div class="form-inline">
                    @Html.ActionLink("Answer This Question", "answer_question", "Answer", new
                   { id = item.id }, new { @class = "btn btn-primary" })

                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

                    @Html.ActionLink("See Other Answers", "See_Other_Answers", "Answer", new
{ id = item.id }, new { @class = "btn btn-danger" })

                    @Html.ActionLink("See His Profile", "SeeProfile", "User", new
                    { id = item.asked_by_who_id }, new { @class = "btn btn-success", @style = "margin-left:350px" })

                </div>
            </div>
        </div>

        <hr />


    }
</div>

Views/Question/list_of_my_question.cshtml
@model IEnumerable<Asp.net_Project.Models.Question>

@{
    ViewBag.Title = "list_of_my_question";
}
<br />
<br />
<h2>List Of My Question</h2>
@{
    <h4>
        Total Question :
        @Model.ToList().Count.ToString()
        Questions

    </h4>
}
<table class="table ">
    <thead class="thead-dark">
        <tr>

            <th>
                Question Title
            </th>
            <th>
                Question Details
            </th>

            <th>
                Categorie
            </th>
            <th>
                Class Destination Or Promotion
            </th>

            <th>
                DataTime
            </th>

            <th>
                Option
            </th>


        </tr>
    </thead>

    @foreach (var item in Model)
    {
        <tr>


            <td>
                @Html.DisplayFor(modelItem => item.queston_title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.question_detail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.categorie)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.classedestination)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.asking_date)
            </td>
            <td>

                @Html.ActionLink("See Answers ", "See_Other_Answers", "Answer", new { id = item.id }, new { @class = "btn btn-primary" })
                <br /><br />
                @Html.ActionLink("Reply to your question ", "answer_question", "Answer", new { id = item.id }, new { @class = "btn btn-success" })

            </td>
        </tr>
    }

</table>

Views/Question/show.cshtml
@model IEnumerable<Asp.net_Project.Models.Question>

@{
    ViewBag.Title = "show";
}
<br />
<br />
<h2>show</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.asked_by_who_id)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.asked_by_who_name)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.categorie)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.classedestination)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.queston_title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.question_detail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.asking_date)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.asked_by_who_id)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.asked_by_who_name)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.categorie)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.classedestination)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.queston_title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.question_detail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.asking_date)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                @Html.ActionLink("Details", "Details", new { id = item.id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.id })
            </td>
        </tr>
    }

</table>